package com.stash.core.data.sync.workers

import android.content.Context
import android.util.Log
import androidx.hilt.work.HiltWorker
import androidx.room.withTransaction
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.stash.core.data.blocklist.BlocklistKey
import com.stash.core.data.blocklist.FileDeleter
import com.stash.core.data.db.StashDatabase
import com.stash.core.data.db.dao.DownloadQueueDao
import com.stash.core.data.db.dao.PlaylistDao
import com.stash.core.data.db.dao.TrackBlocklistDao
import com.stash.core.data.db.dao.TrackDao
import com.stash.core.data.db.dao.fileUsedByAnotherTrack
import dagger.assisted.Assisted
import dagger.assisted.AssistedInject

/**
 * v0.9.15: One-shot cleanup for tracks that leaked back during the
 * v0.9.13/14 broken-flag era. Walks every `tracks` row, derives its
 * stored canonical key, and if that key is in `track_blocklist` tears
 * down the row + cross-refs + queue rows + on-disk file.
 *
 * Why we don't go through [com.stash.core.data.blocklist.BlocklistGuard.block]:
 * `block()` derives the blocklist row's key by re-running TrackMatcher
 * on the raw artist/title strings, but the migrated rows in
 * `track_blocklist` were keyed by SQL-side concatenation of the stored
 * `canonical_artist || '|' || canonical_title` columns. If the stored
 * canonicals were generated by an older TrackMatcher, the two keys
 * disagree and `block()` would insert a duplicate row instead of being
 * idempotent. This worker uses the stored-canonical derivation
 * directly via [BlocklistKey.fromStoredCanonicals], which produces the
 * same key shape as the migration.
 *
 * Schedules itself with [androidx.work.ExistingWorkPolicy.KEEP] from
 * StashApplication.onCreate so it runs exactly once per install +
 * upgrade, idempotent on re-runs (matching rows are gone after the
 * first pass).
 */
@HiltWorker
class BlocklistIntegrityWorker @AssistedInject constructor(
    @Assisted appContext: Context,
    @Assisted params: WorkerParameters,
    private val database: StashDatabase,
    private val trackDao: TrackDao,
    private val blocklistDao: TrackBlocklistDao,
    private val playlistDao: PlaylistDao,
    private val downloadQueueDao: DownloadQueueDao,
    private val fileDeleter: FileDeleter,
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val keys = blocklistDao.getAllKeys().toSet()
        if (keys.isEmpty()) {
            Log.d(TAG, "Blocklist empty — nothing to clean")
            return Result.success()
        }

        val candidates = trackDao.getAllForIntegrityScan()
        var cleaned = 0
        for (t in candidates) {
            val key = BlocklistKey.fromStoredCanonicals(t.canonicalArtist, t.canonicalTitle)
            if (key !in keys) continue

            // Off-transaction file deletes (slow I/O), then atomic row
            // teardown. Mirrors BlocklistGuard.block's ordering. A file another
            // song still plays from stays (two rows can share one); it goes
            // with the last of them.
            t.filePath?.takeUnless { trackDao.fileUsedByAnotherTrack(it, t.id) }?.let(fileDeleter::delete)
            fileDeleter.delete(t.albumArtPath)
            database.withTransaction {
                playlistDao.deleteAllCrossRefsForTrack(t.id)
                downloadQueueDao.deleteByTrackId(t.id)
                trackDao.deleteById(t.id)
            }
            cleaned++
        }
        Log.i(TAG, "BlocklistIntegrityWorker cleaned $cleaned leaked tracks")
        return Result.success()
    }

    private companion object {
        const val TAG = "BlocklistIntegrity"
    }
}
