package com.stash.core.model

data class Playlist(
    val id: Long = 0,
    val name: String,
    val source: MusicSource,
    val sourceId: String = "",
    val type: PlaylistType = PlaylistType.CUSTOM,
    val mixNumber: Int? = null,
    val lastSynced: Long? = null,
    val trackCount: Int = 0,
    val isActive: Boolean = true,
    /**
     * Primary cover URL. For daily mixes that have a 2-tile mosaic stored
     * in the DB as `"url1|url2"`, this is the first (primary) tile so
     * single-image callers (`AsyncImage(model = playlist.artUrl)`) continue
     * to work unchanged. Mosaic-aware callers should read [artTileUrls].
     */
    val artUrl: String? = null,
    /**
     * All cover tile URLs (length 0..2). For daily mixes this is the first
     * 2 unique album covers from the current tracklist and updates every
     * sync; for other playlists it mirrors [artUrl] (at most one entry).
     */
    val artTileUrls: List<String> = emptyList(),
    val syncEnabled: Boolean = false,
    val tracks: List<Track> = emptyList(),
    /**
     * Epoch-millis timestamp of when this playlist was first added to
     * the library. Stable across syncs; drives the Library tab's
     * "Recently added" sort. See [com.stash.core.data.db.entity.PlaylistEntity.dateAdded].
     */
    val dateAdded: Long = System.currentTimeMillis(),
)

enum class PlaylistType {
    DAILY_MIX,
    LIKED_SONGS,
    CUSTOM,

    /**
     * Materialized Stash Mix — rotating, recipe-driven playlist produced
     * locally by the MixGenerator. Separate from DAILY_MIX so the UI can
     * distinguish "imported from Spotify/YouTube" from "generated by
     * Stash itself," and so the protected-cascade rule (v0.3.8) doesn't
     * treat mixes as user-curated untouchables.
     */
    STASH_MIX,
}
